
(define (problem assem-11)
   (:domain assembly)
   (:objects tube connector valve thingumbob foobar whatsis
             hoozawhatsie coil hack device plug mount sprocket frob unit
             contraption wire fastener socket - assembly
             charger tweezers pliers - resource)
   (:init (available valve)
          (available thingumbob)
          (available whatsis)
          (available hoozawhatsie)
          (available hack)
          (available device)
          (available plug)
          (available mount)
          (available frob)
          (available unit)
          (available contraption)
          (available wire)
          (available fastener)
          (available socket)
          (requires connector pliers)
          (requires foobar tweezers)
          (requires coil pliers)
          (requires sprocket charger)
          (part-of connector tube)
          (part-of foobar tube)
          (part-of coil tube)
          (part-of sprocket tube)
          (part-of valve connector)
          (part-of thingumbob connector)
          (part-of device connector)
          (part-of whatsis foobar)
          (part-of hoozawhatsie foobar)
          (part-of hack foobar)
          (transient-part hack coil)
          (transient-part device coil)
          (part-of plug coil)
          (part-of mount coil)
          (part-of frob sprocket)
          (part-of unit sprocket)
          (part-of contraption sprocket)
          (part-of wire sprocket)
          (part-of fastener sprocket)
          (part-of socket sprocket)
          (assemble-order coil sprocket tube)
          (assemble-order device plug connector)
          (assemble-order device plug connector)
          (assemble-order hack mount foobar)
          (assemble-order hack mount coil)
          (remove-order mount hack coil)
          (assemble-order device plug coil)
          (assemble-order device plug coil)
          (remove-order plug device coil)
          (assemble-order plug hack coil)
          (assemble-order unit frob sprocket)
          (assemble-order wire contraption sprocket)
          (assemble-order socket frob sprocket))
   (:goal (complete tube)))
