(define (problem eleven)
  (:domain blocks_world)
  (:objects A B C D E F G H I J K)
  (:init (on-table A)
	 (on B A)
	 (on C B)
	 (clear C)
	 (on-table D)
	 (on E D)
	 (on J E)
	 (on K J)
	 (clear K)
	 (on-table F)
	 (on G F)
	 (on H G)
	 (on I H)
	 (clear I))
  (:goal (and (on E J)
	      (on A E)
	      (on I D)
	      (on H I)
	      (on C K)
	      (on K G)
	      (on B C))))
