(define (problem nine) 
   (:domain blocks_world)
   (:objects A B C D E F G H I)
   (:init (on-table A) 
          (on B A)
          (on C B)
          (clear C) 
          (on-table D)
          (on E D)
          (clear E)
          (on-table F)
          (on G F)
	  (on H G)
	  (on I H)
  	  (clear I))
   (:goal (and (on A E) 
               (on I D)
               (on H I)
               (on C G)
               (on B C))))


