;; satplan bw_large.a blocks

(define (problem nine) 
  (:domain blocks_world)
  (:objects A B C D E F G H I)
  (:init (clear C)
         (on C B) 
	 (on B A)
         (on-table A)
	 (clear E) 
	 (on E D)
         (on-table D)
         (clear I)
	 (on I H)
	 (on H G)
	 (on G F)
	 (on-table F))
  (:goal (and (on A E)
              (on I D)
              (on H I)
              (on C G)
              (on B C))))
