;; satplan bw_large.c blocks

(define (problem fifteen) 
   (:domain blocks_world)
   (:objects A B C D E F G H I J K L M N O)
   (:init (on-table M) 
          (on L M)
          (on A L)
          (on B A)
          (on C B)
          (clear C) 
          (on-table O)
          (on N O)
          (on D N)
          (on E D)
          (on J E)
          (on K J)
          (clear K)
          (on-table F)
          (on G F)
	  (on H G)
	  (on I H)
  	  (clear I))
   (:goal (and (on E J)
               (on A E) 
               (on N A) 
               (on I D)
               (on H I)
               (on M H)
               (on O M)
               (on K G)
               (on C K)
               (on B C)
               (on L B))))
