;; satplan bw_large.d blocks

(define (problem nineteen) 
   (:domain blocks_world)
   (:objects A B C D E F G H I J K L M N O P Q R S)
   (:init (on-table M)
	  (on L M)
          (on A L)
          (clear A) 
          (on-table O)
          (on N O)
          (on D N)
          (on E D)
          (on J E)
          (on K J)
          (clear K)
          (on-table F)
          (on G F)
	  (on H G)
	  (on I H)
  	  (clear I)
          (on-table B)
          (on C B)
          (on P C)
          (on Q P)
          (on R Q)
          (on S R)
          (clear S))
   (:goal (and (on E J)
               (on A E)
               (on N A) 
               (on S N) 
               (on R S) 
               (on Q R) 
               (on I D)
               (on H I)
               (on M H)
               (on O M)
               (on K G)
               (on P K)
               (on C P)
               (on B C)
               (on L B))))



