(define (problem bw_break2)
  (:domain bw_break)
  (:objects A B C D E F G)
  (:init (on-table A) (clear A)
	 (on-table B) (clear B)
	 (on-table C) (clear C)
	 (on-table D) (clear D)
	 (on-table E) (clear E)
	 (on-table F) (clear F)
	 (on-table G) (clear G)
	 )
  (:goal (and (on A B) (on B C) (on C D)))
)
