(define (problem bw_hard_04)
  (:domain blocks_world_hard)
  (:objects A B C D E F)
  (:init (on-table A)
         (on F A)
         (above F A)
         (on E F)
         (above E F)
         (above E A)
         (on D E)
         (above D E)
         (above D F)
         (above D A)
         (on C D)
         (above C D)
         (above C E)
         (above C F)
         (above C A)
         (on B C)
         (above B C)
         (above B D)
         (above B E)
         (above B F)
         (above B A)
         (clear B)
  )
  (:goal (and (clear A) 
              (on A B) 
              (above A B)
              (above A C)
              (above A D)
              (above A E)
              (above A F)
              (on B C) 
              (above B C)
              (above B D)
              (above B E)
              (above B F)
              (on C D)
              (above C D)
              (above C E)
              (above C F)
              (on D E)
              (above D E)
              (above D F)
              (on E F)
              (above E F)
              (on-table F)
         )
  )
)
