(define (problem bw_hard_01)
  (:domain blocks_world_hard)
  (:objects A B C D)
  (:init (on-table A) (clear A)
	       (on-table B) (clear B)
	       (on-table C) (clear C)
	       (on-table D) (clear D)
  )
  (:goal (and (on B C) (on-table A) (on C D)))
)
