(define (problem bw_hard_03)
  (:domain blocks_world_hard)
  (:objects A B C D)
  (:init (on-table A) 
         (on D A)
         (above D A)
         (on C D)
         (above C D)
         (above C A)
         (on B C)
         (above B C)
         (above B D)
         (above B A)
	       (clear B)
  )
  (:goal (and (clear A) 
              (on A B) 
              (above A B)
              (above A C)
              (above A D)
              (on B C) 
              (above B C)
              (above B D)
              (on C D)
              (above C D)
              (on-table D)
         )
  )
)
