(define (problem road-test)
  (:domain travel)
  (:objects a d g car bulldozer)
  (:init (vehicle car) (vehicle bulldozer) 
	 (place a) (place d) (place g)
	 (at car a) (at bulldozer a)
	 (road d g) (road g d)
	 (bridge a d) (bridge d a))
  (:goal (and (at car g) (at bulldozer g)))
  )
